name: ANLPR-cpu

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - pip:
    - opencv-python
    - lxml
    - tqdm
    - tensorflow==2.3.0rc0
    - absl-py
    - easydict
    - pillow
    - pytesseract